name: Run HackerRank Automation Test

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-hackerrank-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install robotframework
          pip install selenium
          pip install robotframework-seleniumlibrary

      - name: Run Robo Test
        run: robot hackerranktest.robot

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: hackerrank-test-output
          path: output.txt
