name: Run HackerRank Automation Test

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Automatic trigger on push to 'main' branch


jobs:
  run-hackerrank-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Timeout after 1 hour

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robo Test
        run: robot hackerranktest.robot

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: hackerrank-test-output
          path: |
            output.xml
            log.html
            report.html
