name: Run HackerRank Automation Test

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-hackerrank-test:
    runs-on: ubuntu-22.04.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apturl  # Install apturl system package

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install webdriver-manager
          pip install robotframework-browser
          pip install geckodriver-autoinstaller
        

      - name: Run Robo Test
        run: robot hackerranktest.robot

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: hackerrank-test-output
          path: output.txt
