name: Run HackerRank Automation Test

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-hackerrank-test:
    runs-on: ubuntu-22.04.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          # Install dependencies from requirements.txt
          pip install --upgrade pip
          pip install -r requirements.txt
        

      - name: Run Robo Test
        run: robot hackerranktest.robot

       -name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: hackerrank-test-output
          path: |
            output.xml
            log.html
            report.html
